R.V Monaalika 21BCE1946_Assignment_1

In [2]:
import pandas as pd
import numpy as np

# Task 1
data = {
    'Feature1': np.random.rand(10),
    'Feature2': np.random.rand(10),
    'Feature3': np.random.rand(10),
    'Feature4': np.random.rand(10),
    'Feature5': np.random.rand(10)
}

df = pd.DataFrame(data)

df

   Feature1  Feature2  Feature3  Feature4  Feature5
0  0.277092  0.532383  0.712963  0.437758  0.136520
1  0.305516  0.436100  0.612378  0.748729  0.877223
2  0.243370  0.079430  0.385491  0.353314  0.280371
3  0.118910  0.566402  0.790537  0.581526  0.585353
4  0.708405  0.127581  0.526336  0.243168  0.528907
5  0.451265  0.334944  0.999556  0.972112  0.186224
6  0.940288  0.406478  0.205540  0.739915  0.505333
7  0.220599  0.545023  0.863737  0.325712  0.695679
8  0.278902  0.289234  0.983750  0.909562  0.644667
9  0.119823  0.882990  0.509572  0.368588  0.200113

In [3]:
# Task 2
print("Task 2:")
print(df.info())

Task 2:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Feature1  10 non-null     float64
 1   Feature2  10 non-null     float64
 2   Feature3  10 non-null     float64
 3   Feature4  10 non-null     float64
 4   Feature5  10 non-null     float64
dtypes: float64(5)
memory usage: 528.0 bytes
None

In [4]:
# Task 3
print("\nTask 3:")
print(df.describe())

Task 3:
        Feature1   Feature2   Feature3   Feature4   Feature5
count  10.000000  10.000000  10.000000  10.000000  10.000000
mean    0.366417   0.420057   0.658986   0.568038   0.464039
std     0.264848   0.233411   0.259510   0.260216   0.250660
min     0.118910   0.079430   0.205540   0.243168   0.136520
25%     0.226292   0.300661   0.513763   0.357132   0.220178
50%     0.277997   0.421289   0.662670   0.509642   0.517120
75%     0.414828   0.541863   0.845437   0.746525   0.629839
max     0.940288   0.882990   0.999556   0.972112   0.877223

In [5]:
# Task 4
print("\nTask 4:")
print(df.loc[3])

Task 4:
Feature1    0.118910
Feature2    0.566402
Feature3    0.790537
Feature4    0.581526
Feature5    0.585353
Name: 3, dtype: float64

In [6]:
# Task 5
print("\nTask 5:")
print(df.isnull().sum())

Task 5:
Feature1    0
Feature2    0
Feature3    0
Feature4    0
Feature5    0
dtype: int64